//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop.PresentationLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Filepath {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Filepath() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicShop.PresentationLayer.Filepath", typeof(Filepath).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Username and Password.
        /// </summary>
        internal static string BothField {
            get {
                return ResourceManager.GetString("BothField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password.
        /// </summary>
        internal static string BothInvalid {
            get {
                return ResourceManager.GetString("BothInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Brand.
        /// </summary>
        internal static string BrandField {
            get {
                return ResourceManager.GetString("BrandField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Code.
        /// </summary>
        internal static string CodeField {
            get {
                return ResourceManager.GetString("CodeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Customer Name.
        /// </summary>
        internal static string CustomerField {
            get {
                return ResourceManager.GetString("CustomerField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Model.
        /// </summary>
        internal static string ModelField {
            get {
                return ResourceManager.GetString("ModelField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only alphabets.
        /// </summary>
        internal static string OnlyAlphabets {
            get {
                return ResourceManager.GetString("OnlyAlphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter alphanumeric.
        /// </summary>
        internal static string OnlyAlphanumeric {
            get {
                return ResourceManager.GetString("OnlyAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only numbers.
        /// </summary>
        internal static string OnlyNumbers {
            get {
                return ResourceManager.GetString("OnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Password.
        /// </summary>
        internal static string PasswordField {
            get {
                return ResourceManager.GetString("PasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Phone number.
        /// </summary>
        internal static string PhoneField {
            get {
                return ResourceManager.GetString("PhoneField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Output Power in watts.
        /// </summary>
        internal static string PowerField {
            get {
                return ResourceManager.GetString("PowerField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Price.
        /// </summary>
        internal static string PriceField {
            get {
                return ResourceManager.GetString("PriceField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product added successfully.
        /// </summary>
        internal static string ProductAdded {
            get {
                return ResourceManager.GetString("ProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F:\Source\repos\UpsForm\ElectronicShop.DataAccess\ProductList.xml.
        /// </summary>
        internal static string productPath {
            get {
                return ResourceManager.GetString("productPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product sold successfuuly.
        /// </summary>
        internal static string ProductSold {
            get {
                return ResourceManager.GetString("ProductSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity added successfully.
        /// </summary>
        internal static string QuantityAdded {
            get {
                return ResourceManager.GetString("QuantityAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity exceeds the limit.
        /// </summary>
        internal static string QuantityExceeds {
            get {
                return ResourceManager.GetString("QuantityExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Quantity.
        /// </summary>
        internal static string QuantityField {
            get {
                return ResourceManager.GetString("QuantityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F:\Source\repos\UpsForm\ElectronicShop.DataAccess\SalesFile.xml.
        /// </summary>
        internal static string salesPath {
            get {
                return ResourceManager.GetString("salesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Username.
        /// </summary>
        internal static string UserField {
            get {
                return ResourceManager.GetString("UserField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Voltage in volts.
        /// </summary>
        internal static string VoltageField {
            get {
                return ResourceManager.GetString("VoltageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Warranty.
        /// </summary>
        internal static string WarrantyField {
            get {
                return ResourceManager.GetString("WarrantyField", resourceCulture);
            }
        }
    }
}
